name: flogg
description: FlogG - 사진 이야기 공유 앱 (SNS형 스토리 데모)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # ✅ 앱에서 사용할 모든 이미지 경로 등록
  assets:
    - assets/images/
    - assets/logo/
